name: "Continuous Deployment"

on:
  workflow_call:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  ATAR_PROJECT: ${{secrets.ATAR_PROJECT_ID_PROD}}
  ATAR_CREDENTIALS: ${{secrets.ATAR_CREDENTIALS_PROD}}
  ATAR_PROJECT_DEV: ${{secrets.ATAR_PROJECT_ID_DEV}}
  ATAR_CREDENTIALS_DEV: ${{secrets.ATAR_CREDENTIALS_DEV}}
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  RETRY: "retry -l -i=60s -c=3"
  SSH_PRIV_KEY_LIBRARY: ${{secrets.SSH_PRIV_KEY_LIBRARY}}

jobs:
  release-candidate:
    if: ${{ startsWith(github.ref, 'refs/heads/fc') }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Release Candidate
        uses: AtarB2B/github-create-rc-workflow@main
  
  feature-deploy:
    needs: release-candidate
    runs-on: ubuntu-latest
    environment: qa
    container:
      image: ghcr.io/atarb2b/deploy-devops:latest
      credentials:
        username: ${{github.repository_owner}}
        password: ${{env.GITHUB_TOKEN}}
    steps:
      - name: Update Library
        uses: AtarB2B/github-library-workflow@main
        with:
          SSH_PRIV_KEY_LIBRARY: ${{env.SSH_PRIV_KEY_LIBRARY}}

      - name: Flow Deploy
        uses: AtarB2B/github-fc-deploy-workflow@main
        with:
          DEPLOY_ENV: "dev"
          SVC_NAME: ${{github.repository}}
  
  rc-deploy:
    runs-on: ubuntu-latest
    environment: homolog
    if: ${{ startsWith(github.ref, 'refs/heads/rc') }}
    container:
      image: ghcr.io/atarb2b/deploy-devops:latest
      credentials:
        username: ${{github.repository_owner}}
        password: ${{env.GITHUB_TOKEN}}
    steps:
      - name: Flow Deploy
        uses: AtarB2B/github-create-tag-workflow@main
        with:
          GITHUB_TOKEN: ${{env.GITHUB_TOKEN}}
          DEPLOY_ENV: "dev"
          SVC_NAME: ${{github.repository}}
  
  prod-deploy:
    runs-on: ubuntu-latest
    environment: prod-atar
    if: ${{ startsWith(github.ref, 'refs/heads/main') }}
    container:
      image: ghcr.io/atarb2b/deploy-devops:latest
      credentials:
        username: ${{github.repository_owner}}
        password: ${{env.GITHUB_TOKEN}}
    steps:
      - name: Flow Deploy
        uses: AtarB2B/github-create-tag-workflow@main
        with:
          GITHUB_TOKEN: ${{env.GITHUB_TOKEN}}
          DEPLOY_ENV: "prod-atar"
          SVC_NAME: ${{github.repository}}