name: "Continuous Integration"

on:
  push:
    branches:
      - 'fc/**'
      - 'feature/**'
      - 'release/**'
      # - 'main'
  # pull_request:
  #   types:
  #     - opened

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_NAME: ${{github.event.repository.name}}
  SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  SSH_PRIV_KEY_LIBRARY: ${{secrets.SSH_PRIV_KEY_LIBRARY}}

jobs:
  create-feature-candidate:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/feature') }}
    container:
      image: ghcr.io/atarb2b/deploy-devops:latest
      credentials:
        username: ${{github.repository_owner}}
        password: ${{env.GITHUB_TOKEN}}
    steps:

      - name: Create feature candidate
        uses: AtarB2B/github-create-fc-workflow@main

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        uses: AtarB2B/github-unit-tests-workflow@main
        with:
          SSH_PRIV_KEY_LIBRARY: ${{secrets.SSH_PRIV_KEY_LIBRARY}}
  
  sonar-scan:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Run Sonar Scanner
        uses: AtarB2B/github-sonar-scan-workflow@main
        with:
          github-repo-name: devops-labs