name: Cron
on:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  execute_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Execute action
        run: |
          echo "=======teste======="
          echo "=======teste======="
          echo "=======teste======="
          echo "=======teste======="
          echo "=======teste======="
          
