name: "Continuous Integration"

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: authorizer-image-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Test Docker image
        run: docker run $IMAGE_NAME sh -c "python --version"

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/heads/feature') != true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Unit Tests
        uses: AtarB2B/github-unit-tests-workflow@minimal
        with:
          SSH_PRIV_KEY_LIBRARY: ${{env.SSH_PRIV_KEY_LIBRARY}}
  
  sonar-scan:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature') != true
    needs: unit-test
    continue-on-error: true
    steps:
      - name: Run Sonar Scanner
        uses: AtarB2B/github-sonar-scan-workflow@main
        with:
          github-repo-name: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{env.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{env.SONAR_TOKEN}}

  qa-deploy:
    needs: release-candidate
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/qa') }}
    environment: qa
    container:
      image: ghcr.io/atarb2b/deploy-devops:latest
      credentials:
        username: ${{github.repository_owner}}
        password: ${{env.GITHUB_TOKEN}}
    steps:
      - name: Flow Deploy
        uses: AtarB2B/github-deploy-k8s@main
        with:
          ATAR_PROJECT: ${{secrets.ATAR_PROJECT_ID_PROD}}
          ATAR_CREDENTIALS: ${{secrets.ATAR_CREDENTIALS_PROD}}
          IMAGE_NAME: gcr.io/${{secrets.ATAR_PROJECT_ID_PROD}}/authorizer

  staging-deploy:
    needs: release-candidate
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/staging') }}
    environment: staging
    container:
      image: ghcr.io/atarb2b/deploy-devops:latest
      credentials:
        username: ${{github.repository_owner}}
        password: ${{env.GITHUB_TOKEN}}
    steps:
      - name: Flow Deploy
        uses: AtarB2B/github-deploy-k8s@main
        with:
          ATAR_PROJECT: ${{secrets.ATAR_PROJECT_ID_PROD}}
          ATAR_CREDENTIALS: ${{secrets.ATAR_CREDENTIALS_PROD}}
          IMAGE_NAME: gcr.io/${{secrets.ATAR_PROJECT_ID_PROD}}/authorizer

  production-deploy:
    needs: release-candidate
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/main') }}
    environment: production
    container:
      image: ghcr.io/atarb2b/deploy-devops:latest
      credentials:
        username: ${{github.repository_owner}}
        password: ${{env.GITHUB_TOKEN}}
    steps:
      - name: Flow Deploy
        uses: AtarB2B/github-deploy-k8s@main
        with:
          ATAR_PROJECT: ${{secrets.ATAR_PROJECT_ID_PROD}}
          ATAR_CREDENTIALS: ${{secrets.ATAR_CREDENTIALS_PROD}}
          IMAGE_NAME: gcr.io/${{secrets.ATAR_PROJECT_ID_PROD}}/authorizer