name: "Continuous Integration"

on:
  workflow_call:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_NAME: ${{github.event.repository.name}}
  SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  SSH_PRIV_KEY_LIBRARY: ${{secrets.SSH_PRIV_KEY_LIBRARY}}

  ATAR_PROJECT: ${{secrets.ATAR_PROJECT_ID_PROD}}
  ATAR_CREDENTIALS: ${{secrets.ATAR_CREDENTIALS_PROD}}
  ATAR_PROJECT_DEV: ${{secrets.ATAR_PROJECT_ID_DEV}}
  ATAR_CREDENTIALS_DEV: ${{secrets.ATAR_CREDENTIALS_DEV}}

  RETRY: "retry -l -i=60s -c=3"

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/rc') }}
    steps:
      - uses: actions/checkout@v1
      
      - name: "DRAFT"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{env.GITHUB_TOKEN}}
          exclude_types: "release|prerelease"
          view_top: 1000
      
      - name: "RELEASE"
        id: last_release2
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{env.GITHUB_TOKEN}}
          exclude_types: "draft|prerelease"
          view_top: 1000

      - name: "PRE-RELEASE"
        id: last_release3
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{env.GITHUB_TOKEN}}
          exclude_types: "release|draft"
          view_top: 1000

      - name: "Print result"
        run: |
          echo "DRAFT ${{ steps.last_release.outputs.name }} = ${{ steps.last_release.outputs.tag_name }}"
          echo "RELEASE ${{ steps.last_release2.outputs.name }} = ${{ steps.last_release2.outputs.tag_name }}"
          echo "PRE-RELEASE ${{ steps.last_release3.outputs.name }} = ${{ steps.last_release3.outputs.tag_name }}"