name: "Continuous Integration"

on:
  workflow_call:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_NAME: ${{github.event.repository.name}}
  SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
  SSH_PRIV_KEY_LIBRARY: ${{secrets.SSH_PRIV_KEY_LIBRARY}}

  ATAR_PROJECT: ${{secrets.ATAR_PROJECT_ID_PROD}}
  ATAR_CREDENTIALS: ${{secrets.ATAR_CREDENTIALS_PROD}}
  ATAR_PROJECT_DEV: ${{secrets.ATAR_PROJECT_ID_DEV}}
  ATAR_CREDENTIALS_DEV: ${{secrets.ATAR_CREDENTIALS_DEV}}

  RETRY: "retry -l -i=60s -c=3"

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/heads/rc') }}
    steps:
      - uses: actions/checkout@v1
      
      - name: "call action"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "release"
          view_top: 1
      
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "name: ${{ steps.last_release.outputs.name }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"

  # rc-deploy:
  #   runs-on: ubuntu-latest
  #   if: ${{ startsWith(github.ref, 'refs/heads/rc') }}
  #   container:
  #     image: ghcr.io/atarb2b/deploy-devops:latest
  #     credentials:
  #       username: ${{github.repository_owner}}
  #       password: ${{env.GITHUB_TOKEN}}
  #   steps:
  #     - name: Flow Deploy
  #       uses: AtarB2B/github-create-tag-workflow@main
  #       with:
  #         GITHUB_TOKEN: ${{env.GITHUB_TOKEN}}
  #         DEPLOY_ENV: "dev"
  #         CREATE_RELEASE: "false"
  #         SSH_PRIV_KEY_LIBRARY: ${{secrets.SSH_PRIV_KEY_LIBRARY}}